# Generated by Django 3.1 on 2021-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('West Bengal', 'West Bengal'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Gujrat', 'Gujrat')], default=None, max_length=30),
        ),
    ]
