# Generated by Django 3.1 on 2020-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200918_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='product_images'),
        ),
    ]
