# Generated by Django 3.1 on 2020-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(related_name='books', to='shop.Book'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
