# Generated by Django 3.1 on 2020-12-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201207_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
