# Generated by Django 3.1 on 2020-12-08 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_book_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='count',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.book')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='books',
            #field=models.ManyToManyField(related_name='books', through='shop.Count', to='shop.Book'),
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(related_name='books', through='shop.Count', to='shop.Book'),
        ),
    ]
