# Generated by Django 3.1 on 2020-12-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201208_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.book'),
        ),
    ]
