# Generated by Django 3.1 on 2020-12-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201208_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(null=True, related_name='books', through='shop.Count', to='shop.Book'),
        ),
    ]
