# Generated by Django 3.1 on 2020-12-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201208_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.book'),
        ),
    ]
