# Generated by Django 3.1 on 2021-01-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201226_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
