# Generated by Django 3.1 on 2021-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available to buy'), ('unavailable', 'Out of stock')], default='available', max_length=32),
        ),
    ]
